import type { CSSProperties } from 'react';

export const PRINT_STYLES = `
  @media print {
    .no-print { display: none !important; }
    body * { visibility: hidden; }
    #print-strip, #print-strip * { visibility: visible; }
    #print-strip { position: absolute; left: 0; top: 0; width: 100%; }
  }
`;

export const styles: Record<string, CSSProperties> = {
  app: {
    minHeight: '100vh',
    background: '#F5EFE3',
    fontFamily: "'Inter', -apple-system, sans-serif",
    color: '#2D2620',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '14px 24px',
    background: '#FBF7EE',
    borderBottom: '1px solid #E5D9C3',
    position: 'sticky',
    top: 0,
    zIndex: 20,
    flexWrap: 'wrap',
    gap: 10,
  },
  headerLeft: { display: 'flex', alignItems: 'center', gap: 10 },
  logoMark: {
    width: 34,
    height: 34,
    borderRadius: 8,
    background: '#B5482A',
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  projectNameInput: {
    fontSize: 17,
    fontWeight: 700,
    border: 'none',
    background: 'transparent',
    color: '#2D2620',
    outline: 'none',
    fontFamily: 'inherit',
  },
  headerRight: { display: 'flex', gap: 8, flexWrap: 'wrap' },
  iconBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '8px 14px',
    borderRadius: 8,
    border: '1px solid #E5D9C3',
    background: '#fff',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    color: '#2D2620',
  },
  primaryBtn: { background: '#B5482A', color: '#fff', border: 'none' },
  main: { maxWidth: 1100, margin: '0 auto', padding: '28px 24px 60px' },
  uploadZone: {
    border: '2px dashed #C4B8A5',
    borderRadius: 16,
    padding: '60px 24px',
    textAlign: 'center',
    cursor: 'pointer',
    background: '#FBF7EE',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 8,
  },
  uploadText: { fontSize: 15, fontWeight: 600, margin: '8px 0 0' },
  uploadSubtext: { fontSize: 12.5, color: '#8B7355', margin: 0 },
  transport: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 14,
    flexWrap: 'wrap',
  },
  playBtn: {
    width: 42,
    height: 42,
    borderRadius: '50%',
    border: 'none',
    background: '#2D2620',
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  timeLabel: { fontSize: 13, fontVariantNumeric: 'tabular-nums', fontWeight: 600 },
  timeSep: { color: '#C4B8A5' },
  secondaryBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: 5,
    padding: '7px 12px',
    borderRadius: 8,
    border: '1px solid #E5D9C3',
    background: '#fff',
    fontSize: 12.5,
    fontWeight: 600,
    cursor: 'pointer',
    color: '#2D2620',
  },
  timelineWrap: { marginBottom: 24 },
  timeline: {
    position: 'relative',
    height: 90,
    background: '#FBF7EE',
    borderRadius: 10,
    border: '1px solid #E5D9C3',
    overflow: 'hidden',
    cursor: 'pointer',
  },
  waveformLayer: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    alignItems: 'flex-end',
    opacity: 0.5,
  },
  timelineHint: { fontSize: 11.5, color: '#8B7355', marginTop: 6 },
  editorGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 20,
    marginBottom: 28,
  },
  segmentList: {
    background: '#FBF7EE',
    border: '1px solid #E5D9C3',
    borderRadius: 12,
    padding: 16,
    maxHeight: 320,
    overflowY: 'auto',
  },
  segmentEditor: {
    background: '#FBF7EE',
    border: '1px solid #E5D9C3',
    borderRadius: 12,
    padding: 16,
  },
  sectionTitle: { fontSize: 13, fontWeight: 700, margin: '0 0 12px', textTransform: 'uppercase', letterSpacing: 0.4, color: '#8B7355' },
  emptyHint: { fontSize: 13, color: '#8B7355', lineHeight: 1.5 },
  segmentRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 8px',
    borderRadius: 8,
    cursor: 'pointer',
    marginBottom: 2,
  },
  segmentSwatch: {
    width: 22,
    height: 22,
    borderRadius: 6,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  segmentTime: { fontSize: 12, fontVariantNumeric: 'tabular-nums', color: '#8B7355', flexShrink: 0 },
  segmentLabelText: { fontSize: 12.5, flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  deleteBtn: {
    border: 'none',
    background: 'transparent',
    color: '#B5482A',
    cursor: 'pointer',
    padding: 4,
    display: 'flex',
  },
  fieldLabel: { display: 'block', fontSize: 12, fontWeight: 700, marginTop: 14, marginBottom: 6, color: '#8B7355' },
  textInput: {
    width: '100%',
    padding: '9px 12px',
    borderRadius: 8,
    border: '1px solid #E5D9C3',
    background: '#fff',
    color: '#2D2620',
    fontSize: 13,
    fontFamily: 'inherit',
    boxSizing: 'border-box',
  },
  swatchRow: { display: 'flex', gap: 8, flexWrap: 'wrap' },
  shapeBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    border: '1.5px solid #E0D5C0',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  colorBtn: {
    width: 30,
    height: 30,
    borderRadius: '50%',
    border: 'none',
    cursor: 'pointer',
  },
  exportSection: { marginTop: 8 },
  exportHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  printStrip: {
    background: '#fff',
    border: '1px solid #E5D9C3',
    borderRadius: 12,
    padding: 24,
  },
  printTitle: { fontSize: 18, marginTop: 0, marginBottom: 16, textAlign: 'center' },
  printRow: { display: 'flex', gap: 12, flexWrap: 'wrap', justifyContent: 'center' },
  printCell: { textAlign: 'center', width: 90 },
  printShapeBox: {
    width: 80,
    height: 80,
    border: '2px solid',
    borderRadius: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto',
    position: 'relative',
  },
  printIcon: { position: 'absolute', bottom: -6, right: -6, fontSize: 18 },
  printLabel: { fontSize: 10.5, marginTop: 6, color: '#5A4D3D' },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(45,38,32,0.4)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    padding: 20,
  },
  modal: {
    background: '#FBF7EE',
    borderRadius: 14,
    padding: 22,
    width: '100%',
    maxWidth: 420,
    maxHeight: '80vh',
    overflowY: 'auto',
  },
  modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  modalHint: { fontSize: 12.5, color: '#8B7355', marginBottom: 14 },
  closeBtn: { border: 'none', background: 'transparent', cursor: 'pointer', color: '#8B7355' },
  templateRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    width: '100%',
    padding: '10px 12px',
    borderRadius: 9,
    border: '1px solid #E5D9C3',
    background: '#fff',
    marginBottom: 8,
    cursor: 'pointer',
    fontSize: 13,
    textAlign: 'left',
    fontFamily: 'inherit',
  },
  templatePreview: { display: 'flex', gap: 2, flexShrink: 0 },
  templateMeta: { marginLeft: 'auto', fontSize: 11, color: '#8B7355', flexShrink: 0 },
  toast: {
    position: 'fixed',
    bottom: 24,
    left: '50%',
    transform: 'translateX(-50%)',
    background: '#2D2620',
    color: '#fff',
    padding: '10px 20px',
    borderRadius: 24,
    fontSize: 13,
    fontWeight: 600,
    zIndex: 200,
  },
  presentWrap: {
    minHeight: '100vh',
    background: '#1C1710',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    padding: 24,
  },
  exitPresentBtn: {
    position: 'absolute',
    top: 20,
    right: 20,
    background: 'rgba(255,255,255,0.1)',
    border: 'none',
    borderRadius: '50%',
    width: 40,
    height: 40,
    color: '#fff',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  presentStage: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 340,
    position: 'relative',
  },
  presentInstrumentIcon: { fontSize: 56, marginTop: 20 },
  presentLabel: { color: '#fff', fontSize: 22, marginTop: 20, fontWeight: 600, textAlign: 'center' },
  presentStrip: {
    display: 'flex',
    gap: 4,
    width: '90%',
    maxWidth: 700,
    marginTop: 40,
  },
  presentControls: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    marginTop: 24,
  },
  presentPlayBtn: {
    width: 52,
    height: 52,
    borderRadius: '50%',
    border: 'none',
    background: '#fff',
    color: '#1C1710',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  presentTime: { color: '#fff', fontSize: 14, fontVariantNumeric: 'tabular-nums' },
};
